### ISSUE TITLE
More than 2 HDD will not boot

### ISSUE THREAD

**Issue by crazyb123** [AuxXxilium/arc#66] opened 2023-01-23 16:39 UTC
Tested the latest version V23.1.23 ,it cannot use.
config completed -->**① reboot** --> recovery the DSM --> reboot --> update flashdisk --> reboot --> after a while  network card  stop work，IP lose.
Previous versions stop at **① reboot**

**Comment by AuxXxilium** [comment] 2023-01-23 16:41
try to update modules and addons in loader - build loader - and boot again

**Comment by AuxXxilium** [comment] 2023-01-23 17:06
just to know:

Bugreport
Before you report an issue or bug please read the [Wiki](https://github.com/AuxXxilium/AuxXxilium/wiki) and make sure your setting are correct.
If you have to report an issue or bug:
Arc Version
Hardware you use (Networkchip, Sata/HBA/Raid Controller)
Screenshot the Systeminfo (Arc - Systeminfo)
optional: boot arc loader, don't start arc or exit it, type "lspci -nn" and "lspci -nnk" - attach the outputs

**Comment by RJSUTH** [comment] 2023-01-26 11:36
version V23.1.25

i have the same problems with a Thecus N7770-10G with 7 HDDs and a HP5NL with 6 HDDs. 

Intel 6 Series C200 Sata Controller and Marvell Device 9170 (rev12)

Only with one HHD it works, but with all HDDs System hang up. Network Card stop working
With Version V23.1.14 it worked perfectly

**Comment by AuxXxilium** [comment] 2023-01-26 11:42
where have you got the 25? there is no 25. only a 25-dev (development). use 24 and all is working.

**Comment by RJSUTH** [comment] 2023-01-26 11:49
i tried both versions

**Comment by RJSUTH** [comment] 2023-01-26 11:51
with 1 HDD it works 
with 2 HDDS it works
With 3 HDDS ist stops working

**Comment by AuxXxilium** [comment] 2023-01-26 11:59
there is no way with 24. because i use this version on server with 24 hard disk. if you are sure that 24 isn't working, send me a screenshot from Sysinfo(Systeminfo) screen in arc loader.

**Comment by RJSUTH** [comment] 2023-01-26 12:20
Gerne

 



 

Von: Christian Schulthess ***@***.***> 
Gesendet: Donnerstag, 26. Januar 2023 13:00
An: AuxXxilium/arc ***@***.***>
Cc: RJSUTH ***@***.***>; Comment ***@***.***>
Betreff: Re: [AuxXxilium/arc] More than 2 HDD will not boot (Issue #66)

 

there is no way with 24. because i use this version on server with 24 hard disk. if you are sure that 24 isn't working, send me a screenshot from Sysinfo(Systeminfo) screen in arc loader.

**Comment by RJSUTH** [comment] 2023-01-26 12:33
![IMG_8985-1](https://user-images.githubusercontent.com/122780513/214836173-3815e19e-a258-4acf-b10e-4cf9025c9d6c.jpg)

**Comment by AuxXxilium** [comment] 2023-01-26 12:42
I see the issue. Can't work without sataportmap. because evvery controller reports 8 slots. so you have more slots that disks can be placed in nas. you should set the portmap manual to 02221. you use pcie to sata adapter? it's possible that this will not work. because of bus issues. it is possible that you have to set all things manual incl. pcie adresses. dsm will not run on every hardware, every syno nas is simple in hardware. the highest drive count in 4021 is only made by 1 hba and 1 extender. 

i will try multiple sata controller later today and look where the problem is with automatic sataportmap dedection.

**Comment by RJSUTH** [comment] 2023-01-26 12:50
Where must i set  portmap manual to 02221?

**Comment by RJSUTH** [comment] 2023-01-26 13:04
i added sataportmap 02221 in Synoinfo, but it does also not work.

With your automated Version 23.1.14 it worked perfectly. But now it wants to update to 23.1.23 , and it stops working

**Comment by AuxXxilium** [comment] 2023-01-26 13:07
automated 14 worked? o.O than go back to this and wait for my next answer. aAm 26.01.2023 um 14:05 schrieb RJSUTH ***@***.***>:﻿
i added sataportmap 02221 in Synoinfo, but it does also not work.
With your automated Version 23.1.14 it worked perfectly. But now it wants to update to 23.1.23 , and it stops working

**Comment by RJSUTH** [comment] 2023-01-26 13:09
now it works not again, because when installing arc wants to update to 23.1.23. And with this version it stops working

**Comment by AuxXxilium** [comment] 2023-01-26 13:10
one try please, add the nvme addon and rebuild loader please. it is possible that your controller are using pcie storage protocol.

**Comment by RJSUTH** [comment] 2023-01-26 13:18
also not working

**Comment by RJSUTH** [comment] 2023-01-26 13:26
sorry i had Version 16 . I hope this doesn't matter

**Comment by AuxXxilium** [comment] 2023-01-26 15:16
> also not working

so to be clear: automated update from 14 to newer is not working without a new stick or boot img replace. the base is changed on 23.01.15 and so we need to do this step.

you used the 23.01.14? right?

**Comment by RJSUTH** [comment] 2023-01-26 15:44
yes

**Comment by AuxXxilium** [comment] 2023-01-26 15:45
> yes

so you have to replace the loader file or stick. no way for inplace upgrade in arc.

**Comment by RJSUTH** [comment] 2023-01-26 15:46
i always made the boot stick new with rufus.

**Comment by AuxXxilium** [comment] 2023-01-26 15:49
my problem is, there were no changes that can cause this error in your system

**Comment by RJSUTH** [comment] 2023-01-27 06:18
Phantastic, it works now. Great work. 

What was the problem?

**Comment by AuxXxilium** [comment] 2023-01-27 06:21
> Phantastic, it works now. Great work. 
> 
> 
> 
> What was the problem?
if you will send me a screenshot from sysinfo, i can tell you. i changed the drivers and hardwaredb. both is possible.

**Comment by RJSUTH** [comment] 2023-01-27 07:00
![IMG_8987](https://user-images.githubusercontent.com/122780513/215027621-3acd2358-0259-4b62-bfaa-af98a1d171df.jpg)

**Comment by AuxXxilium** [comment] 2023-01-27 07:03
> ![IMG_8987](https://user-images.githubusercontent.com/122780513/215027621-3acd2358-0259-4b62-bfaa-af98a1d171df.jpg)
> 
> 

so because of no other module is loaded. it was the hardwaredatabase. look like the database was blocking your controller.

**Comment by crazyb123** [comment] 2023-01-27 12:10
Sorry for that，it cannot work.
configed then reboot，recovery the DSM ，Stop afterward.
<img width="590" alt="1631583878(1)" src="https://user-images.githubusercontent.com/119409441/215082629-be0c22ec-183a-4233-894c-13034a4b8f9f.png">

**Comment by RJSUTH** [comment] 2023-01-27 12:24
Sometimes my DS does not boot complete , and i have to shutdown with power Button and start again.

i think there could be problems with HDDs if they have already data on it, specially after upgrade.
I upgraded from DSM 6.2 to 7.1. And I read on another side that Synology changed partition scheme. 

The old partitions for DSM where 2GB and 2,4GB. 
The new partitions are 8Gb and 2GB for DSM.

i will backup my Data and create the storage new. Hope this will help to stop boot hangups for me

**Comment by RJSUTH** [comment] 2023-01-27 12:28
My DS has a VGA Port to connect a Monitor. 

Is it possible to leave the boot messages on VGA, not to switch to serial console?

This would be easyier for find out where Booting stops

**Comment by AuxXxilium** [comment] 2023-01-27 12:32
no is not possible to output serial on vga.

**Comment by crazyb123** [comment] 2023-01-27 12:54
> > Sorry for that，it cannot work.
> > configed then reboot，recovery the DSM ，Stop afterward.
> > <img alt="1631583878(1)" width="590" src="https://user-images.githubusercontent.com/119409441/215082629-be0c22ec-183a-4233-894c-13034a4b8f9f.png">
> 
> set sataportmap to 52 and try again

It still can't work.

**Comment by AuxXxilium** [comment] 2023-01-27 17:12
> > > Sorry for that，it cannot work.
> > > configed then reboot，recovery the DSM ，Stop afterward.
> > > <img alt="1631583878(1)" width="590" src="https://user-images.githubusercontent.com/119409441/215082629-be0c22ec-183a-4233-894c-13034a4b8f9f.png">
> > 
> > 
> > set sataportmap to 52 and try again
> 
> It still can't work.

read here if your settings are correct: https://github.com/AuxXxilium/AuxXxilium/wiki/Settings:-Bios-and-UEFI

if everything is correct, i don't know where your issue is.

**Comment by AuxXxilium** [comment] 2023-01-27 17:15
> Sometimes my DS does not boot complete , and i have to shutdown with power Button and start again.
> 
> i think there could be problems with HDDs if they have already data on it, specially after upgrade. I upgraded from DSM 6.2 to 7.1. And I read on another side that Synology changed partition scheme.
> 
> The old partitions for DSM where 2GB and 2,4GB. The new partitions are 8Gb and 2GB for DSM.
> 
> i will backup my Data and create the storage new. Hope this will help to stop boot hangups for me

yes thats normal with this amount of controller, they are to much to handle for dsm. dsm can only address up to 8 pci paths. so this issue is belong to dsm in all. actual there is no way to patch this.

**Comment by crazyb123** [comment] 2023-01-28 03:41
> > > > Sorry for that，it cannot work.
> > > > configed then reboot，recovery the DSM ，Stop afterward.
> > > > 
> > > 
> > > 
> > > set sataportmap to 52 and try again
> > 
> > 
> > It still can't work.
> 
> read here if your settings are correct: https://github.com/AuxXxilium/AuxXxilium/wiki/Settings:-Bios-and-UEFI
> 
> if everything is correct, i don't know where your issue is.
Inside my setting，C1E is always on，next time I‘ll disable it.

**Comment by crazyb123** [comment] 2023-01-29 00:24
Disable C1E ，ASPM，LPM，disable all unused devices.
USE UEFI or Legacy，still cannot work.
not use External Ethernet card，use Motherboard integrated Ethernet card rt8169 not work too.

**Comment by RJSUTH** [comment] 2023-01-31 12:28
am back again with same issue with a qnap TS451 with 4 HDDs.

 With V23.011.14 automated DSM boots and works.

I made a new Boot USB Stick with Version V23.01.30 , the device don't boot.

i compared SataPortMap between V14 and V30. 

In V14 SataPortMap="2" DSM came up
In V30 SataPortMap ="022" DSM stopped Booting.

I Changed in V30 SataPortMap ="2" and DSM boots now.

Can you tell me why this is so?

**Comment by RJSUTH** [comment] 2023-01-31 12:38
> 
![IMG_9034](https://user-images.githubusercontent.com/122780513/215761757-45dc48d6-b570-450a-b487-a6a75fa68b11.jpg)

![IMG_9035](https://user-images.githubusercontent.com/122780513/215761773-e38a21ba-5817-4ec6-985f-1ceb05cbfe3c.jpg)
![IMG_9036](https://user-images.githubusercontent.com/122780513/215761798-25877466-c8d1-45c7-8b01-71e96e2829be.jpg)

**Comment by RJSUTH** [comment] 2023-01-31 12:38
when ARC boots it shows IP, e.g. 192.168.100.111. When ist boots DSM IP changes to e.g.: 192.168.100.112 or other
Can you fix this, because i must always start IP-Scanner to find the right IP Address

**Comment by RJSUTH** [comment] 2023-01-31 12:41
i have more XPenology devices: Can you check before building ARC Image , if there are MACs and serials present and adjust that?

**Comment by AuxXxilium** [comment] 2023-01-31 12:42
> when ARC boots it shows IP, e.g. 192.168.100.111. When ist boots DSM IP changes to e.g.: 192.168.100.112 or other
> 
> Can you fix this, because i must always start IP-Scanner to find the right IP Address

no this is wanted by more users, so we can build loader with arc patch and mac changes without losing connection to web terminal.and set the new mac while first boot.

**Comment by AuxXxilium** [comment] 2023-01-31 12:43
> 
> 
> 
> 
> > 
> 
> ![IMG_9034](https://user-images.githubusercontent.com/122780513/215761757-45dc48d6-b570-450a-b487-a6a75fa68b11.jpg)
> 
> 
> 
> ![IMG_9035](https://user-images.githubusercontent.com/122780513/215761773-e38a21ba-5817-4ec6-985f-1ceb05cbfe3c.jpg)
> 
> ![IMG_9036](https://user-images.githubusercontent.com/122780513/215761798-25877466-c8d1-45c7-8b01-71e96e2829be.jpg)
> 
> 

first sata controller has no drive connected. i will change something today but it's tricky.

**Comment by AuxXxilium** [comment] 2023-01-31 19:37
> when ARC boots it shows IP, e.g. 192.168.100.111. When ist boots DSM IP changes to e.g.: 192.168.100.112 or other Can you fix this, because i must always start IP-Scanner to find the right IP Address

next build will let you choose if you want to reload ip

**Comment by AuxXxilium** [comment] 2023-01-31 19:38
> i have more XPenology devices: Can you check before building ARC Image , if there are MACs and serials present and adjust that?

there is no way to do this, we can not access dsm commands from loader side.

**Comment by AuxXxilium** [comment] 2023-01-31 19:39
> > 
> 
> ![IMG_9034](https://user-images.githubusercontent.com/122780513/215761757-45dc48d6-b570-450a-b487-a6a75fa68b11.jpg)
> 
> ![IMG_9035](https://user-images.githubusercontent.com/122780513/215761773-e38a21ba-5817-4ec6-985f-1ceb05cbfe3c.jpg) ![IMG_9036](https://user-images.githubusercontent.com/122780513/215761798-25877466-c8d1-45c7-8b01-71e96e2829be.jpg)

next build should remove Sata Controller with 0 drives from SataPortMap

**Comment by RJSUTH** [comment] 2023-01-31 20:41
> > i have more XPenology devices: Can you check before building ARC Image , if there are MACs and serials present and adjust that?
> 
> there is no way to do this, we can not access dsm commands from loader side.

 in Synology assistant we can see these parameters, Mac address must be unique, can serial be by all Instances the same?

**Comment by AuxXxilium** [comment] 2023-01-31 20:44
> > > i have more XPenology devices: Can you check before building ARC Image , if there are MACs and serials present and adjust that?
> > 
> > 
> > there is no way to do this, we can not access dsm commands from loader side.
> 
> in Synology assistant we can see these parameters, Mac address must be unique, can serial be by all Instances the same?

yes, but the assistant is part of dsm. no access to this.

yes, serial have not to be unique.

**Comment by RJSUTH** [comment] 2023-01-31 21:06
> > > 
> > 
> > 
> > ![IMG_9034](https://user-images.githubusercontent.com/122780513/215761757-45dc48d6-b570-450a-b487-a6a75fa68b11.jpg)
> > ![IMG_9035](https://user-images.githubusercontent.com/122780513/215761773-e38a21ba-5817-4ec6-985f-1ceb05cbfe3c.jpg) ![IMG_9036](https://user-images.githubusercontent.com/122780513/215761798-25877466-c8d1-45c7-8b01-71e96e2829be.jpg)
> 
> next build should remove Sata Controller with 0 drives from SataPortMap

whats strange for me is: i have 4 HDDs , but in SatatPortMap the paramter is 2

**Comment by AuxXxilium** [comment] 2023-01-31 21:20
> > > > 
> > > 
> > > 
> > > ![IMG_9034](https://user-images.githubusercontent.com/122780513/215761757-45dc48d6-b570-450a-b487-a6a75fa68b11.jpg)
> > > ![IMG_9035](https://user-images.githubusercontent.com/122780513/215761773-e38a21ba-5817-4ec6-985f-1ceb05cbfe3c.jpg) ![IMG_9036](https://user-images.githubusercontent.com/122780513/215761798-25877466-c8d1-45c7-8b01-71e96e2829be.jpg)
> > 
> > 
> > next build should remove Sata Controller with 0 drives from SataPortMap
> 
> whats strange for me is: i have 4 HDDs , but in SatatPortMap the paramter is 2

it is possible that your controller don't need any portmap and you can remove it from config.

**Comment by RJSUTH** [comment] 2023-01-31 21:23
> 

But if a change back Portmap to 022 DSM does not boot. somehow this parameter causes a function

**Comment by AuxXxilium** [comment] 2023-01-31 21:24
> > 
> 
> But if a change back Portmap to 022 DSM does not boot. somehow this parameter causes a function

because of 0 in first place

**Comment by RJSUTH** [comment] 2023-01-31 21:25
Ok, i will try this and report you back tomorrow

**Comment by crazyb123** [comment] 2023-02-01 01:55
On my platform，I can delete the configs **supportraidgroup sataportmap support_ssd_cache**, DSM will still work.

mainboard：asus B85M-e（4port sata3.0，2port sata2.0）
cpu：intel 1265l v3 （Integrated display）
network card：i350-t2 （Link aggregation）
Expansion cards：JMB582 （2port sata3.0）

**Comment by RJSUTH** [comment] 2023-02-01 07:42
> > > 
> > 
> > 
> > But if a change back Portmap to 022 DSM does not boot. somehow this parameter causes a function
> 
> because of 0 in first place

i can change SataPortMap to 4 or delete it, and DSM works.

**Comment by RJSUTH** [comment] 2023-02-02 14:30
Super! With v23.02.01-igb SataPortMap shows 22 so DSM can boot now.

But one more problem, because the MAC is already assigned to another unit. the new unit is not available to Web Interface.
i have to change MAC manually in Userconfig. Then it works perfectly.

Question : Is there a way for you to scan IPs and MACs network and change MAC automatically to unused parameters?

**Comment by RJSUTH** [comment] 2023-02-02 14:37
another question:
The QNAP451 uses for boot an internal USB Disk Module PMAP wich i want to leave there for dual booting Qnap or Sysnolgy DSM.

Is there a way to suppress it because i don't want to show this usbshares in File Manger when DSM is started ?

![pmap](https://user-images.githubusercontent.com/122780513/216353420-c649faac-e48b-4a9f-8a06-bf1321877283.png)

**Comment by AuxXxilium** [comment] 2023-02-02 14:39
> another question:
> 
> The QNAP451 uses for boot an internal USB Disk Module PMAP wich i want to leave there for dual booting Qnap or Sysnolgy DSM.
> 
> 
> 
> Is there a way to suppress it because i don't want to show this usbshares in File Manger when DSM is started ?
> 
> 
> 
> ![pmap](https://user-images.githubusercontent.com/122780513/216353420-c649faac-e48b-4a9f-8a06-bf1321877283.png)
> 
> 

Set Access for this in DSM to Noone.

**Comment by RJSUTH** [comment] 2023-02-04 19:16
is there a way to change serial while DSM is booted per ssh ?

**Comment by AuxXxilium** [comment] 2023-02-04 19:45
> is there a way to change serial while DSM is booted per ssh ?

no

**Closed** 2023-02-09 18:34 UTC
