### ISSUE TITLE
Virtual machine crashes after DSM installation

### ISSUE THREAD

**Issue by serviceiotcc** [AuxXxilium/arc#293] opened 2023-05-31 15:19 UTC
My bootloader lives in a ESXi. After installing the DSM and the countdown, this page appears:

![image](https://github.com/AuxXxilium/arc/assets/74203855/a4723073-afb8-4825-8097-7d343a867701)

Then the virtual machine turns off. Restart does the same. Tried different versions of the operating system (7.2, 7.1.1), the behavior is the same. Bootloader version 23.5.106a. Storage Model DS3617xs

**Comment by AuxXxilium** [comment] 2023-05-31 16:14
Use older one or provide the informations i mentioned in guideline for bugreport

**Comment by serviceiotcc** [comment] 2023-05-31 16:19
First: Information from Wiki for bugreport:

Arc Version: 23.5.106a
Hardware you use (Networkchip, Sata/HBA/Raid Controller): Network: E1000e, Sata vmdk drives.
Screenshot the Systeminfo (Arc - Systeminfo):
![image](https://github.com/AuxXxilium/arc/assets/74203855/46928a8b-e79c-4191-9166-0830fcb54442)
![image](https://github.com/AuxXxilium/arc/assets/74203855/4e0fa449-94e3-4b0c-8a29-f06b95061a37)

second: I tried to open in incognito mode, the behavior is the same

**Comment by AuxXxilium** [comment] 2023-05-31 16:23
Why do you boot a vm in legacy mode?

**Comment by serviceiotcc** [comment] 2023-05-31 16:26
I did not attach any importance to this. Do you recommend EFI mode?

**Comment by AuxXxilium** [comment] 2023-05-31 18:20
everytime. like i wrote in wiki.

**Comment by serviceiotcc** [comment] 2023-05-31 21:36
I tried the new version, on another server, but also in ESXi. The problem persists, here's the info:

Arc Version: 23.5.107
Hardware you use (Networkchip, Sata/HBA/Raid Controller): Network: E1000e, Sata vmdk drives.
Screenshot the Systeminfo (Arc - Systeminfo):

![image](https://github.com/AuxXxilium/arc/assets/74203855/d9bf6ca5-6d13-4318-9207-93da6f8bb91c)

**Comment by AuxXxilium** [comment] 2023-06-01 05:09
check your vm settings. there must be an issue. i use multiple vm to test and everything works.

**Comment by AuxXxilium** [comment] 2023-06-01 05:12
Howto - VM für Xpenology in ESXi erstellen - Arc/ARPL Redpill Loader  - ESXi - Xpenology
https://youtu.be/6f2jlL2PuTs

**Comment by AuxXxilium** [comment] 2023-06-01 05:19
And why do you use such an old system? why no broadwellnk like DS3622xs+ / RS4021xs+?

**Comment by serviceiotcc** [comment] 2023-06-01 09:42
I tried to copy the settings from your video, with the new version of the bootloader, the problem persists.

Arc Version: 23.6.0
Hardware you use (Networkchip, Sata/HBA/Raid Controller): Network: VMXNET3, Sata vmdk drives.
Screenshot the Systeminfo (Arc - Systeminfo):
![image](https://github.com/AuxXxilium/arc/assets/74203855/32003650-55cd-491c-ad91-94c41b16c2c7)

![image](https://github.com/AuxXxilium/arc/assets/74203855/f20276ec-96b7-46f9-b514-46ce9d912367)
![image](https://github.com/AuxXxilium/arc/assets/74203855/1d6f675f-0bc8-446e-a723-33afca2e316f)
![image](https://github.com/AuxXxilium/arc/assets/74203855/1997bce1-c411-4ce6-87c9-7c6147176b0d)
![image](https://github.com/AuxXxilium/arc/assets/74203855/fe720f00-50fe-4795-ab20-9b55c3722466)

**Comment by serviceiotcc** [comment] 2023-06-01 11:09
With the same settings, bootloader version 23.5.33 works without problems with DSM 7.1.1

**Comment by AuxXxilium** [comment] 2023-06-01 11:43
and again, why do you use this old ds? we dropped some support, because of 7.2.0 rework.

**Comment by serviceiotcc** [comment] 2023-06-01 11:56
Because in the old version of the bootloader, the operating system is not version 7.2, but 7.2. RC. With the latest bootloader, the problem persists on both versions of the DSM.

I was just testing to see if the problem persists on older versions of the bootloader. There is no problem. Therefore, the problem is in newer versions. I am ready to provide any information you ask.

**Comment by AuxXxilium** [comment] 2023-06-01 12:05
why do you use this old 3617? that was the question.

**Comment by AuxXxilium** [comment] 2023-06-01 12:28
and you will tell me that ds3622 is not working for you?

**Comment by serviceiotcc** [comment] 2023-06-01 12:30
Everything is correct. DS3622xs+ works on 23.5.33 and DS3622xs+ doesn't work on 23.5.107, 23.6.0, 23.5.106

**Comment by AuxXxilium** [comment] 2023-06-01 12:42
what does not work. make this more clear please.

btw you can add a serial port to this vm and provide the log.

**Comment by AuxXxilium** [comment] 2023-06-01 12:44
my problem is, that everyone else has it working in vm, i try everytime ds3622 in vm with efi and without efi. and the ds2422 because of dt model.

everything is working on my system. so i can't follow there your issue is.

**Comment by serviceiotcc** [comment] 2023-06-01 20:32
For some reason I can't connect the serial port to the file, I get this error even though I tried different file extensions

![image](https://github.com/AuxXxilium/arc/assets/74203855/fedb427a-bff3-4804-90ba-306c4e8d9325)

Let's describe the problem again. The loader is successfully configured, compiled and loaded. After that, the DSM is successfully installed. The countdown begins, and after a while, this page appears:

![image](https://github.com/AuxXxilium/arc/assets/74203855/2e5e512d-fc3f-4195-8ab9-a0c30cbaa58e)

After a few seconds, the virtual machine shuts down. You can start it again, the bootloader will boot successfully and the machine will work. But as soon as I try to enter the web interface of the DSM, the same page appears and the virtual machine turns off.

This behavior is observed on the following versions: 23.5.107, 23.6.0, 23.5.106

At the same time, if I use the version 23.5.33, then there is no such problem, and everything works fine.

**Comment by AuxXxilium** [comment] 2023-06-01 20:40
if you can't add a serial port, your vm has a bug. it's must be possible for all vm.

**Comment by AuxXxilium** [comment] 2023-06-01 21:52
wait for 23.6.1 and everything should be fine

**Comment by knekkert** [comment] 2023-06-04 14:03
Hi.
I have the same problem. 
Loader  23.6.20a

Esxi guest vm shuts down when instaling dsm.

**Comment by AuxXxilium** [comment] 2023-06-04 16:24
Provide a serial log from boot up to shutdown. than we can look whats wrong. have you exchanged the .vmdk or tried inplace upgrade?

**Comment by knekkert** [comment] 2023-06-04 16:40
I started with a new vm copyinh the vmdk file,  tried uefi and bios samme result. How do i do the serial log?

**Comment by AuxXxilium** [comment] 2023-06-04 16:46
add serial port to you vm.

please provide screenshot from arc - sysinfo here.

**Comment by AuxXxilium** [comment] 2023-06-04 17:28
Please try with 23.6.21

**Comment by knekkert** [comment] 2023-06-04 18:10
[serial.out.txt](https://github.com/AuxXxilium/arc/files/1164
![ARC LOADER sysinfo](https://github.com/AuxXxilium/arc/assets/13943152/4c19f9be-10f6-456c-b08a-d96bfe336a85)
6342/serial.out.txt)

**Comment by knekkert** [comment] 2023-06-04 18:12
[serial.out.txt](https://github.com/AuxXxilium/arc/files/11646348/serial.out.txt)

**Comment by AuxXxilium** [comment] 2023-06-04 18:17
why this portmap?

**Comment by knekkert** [comment] 2023-06-04 18:29
23.6.21 works,  will try one more time. the guest vm did not shutdown now
 i have an lsi sas controller that is not attached to this test vm i will try to attach it now.

**Comment by AuxXxilium** [comment] 2023-06-04 18:33
my lsi 2008 is working. but it is in raid and not it mode. so the modules are different

**Comment by nemesis122** [comment] 2023-06-04 18:38
I can confirm tried with scsi+ or sata 7.1 7.2 with arc patch without in vmware workstation VMM Virtualbox 23.6.20a the virtual maschine close unexpected by the second boot in this step when dsm is installed  BUT on my gen8 this loader works perfect thank you very much tommorow morning 5 clock i will try with 23..6.21

**Comment by nemesis122** [comment] 2023-06-04 19:02
i can confirm with 23.6.21 Vware Workstation the loader is NOT freezing/closing by the second boot thank you very much for this great work.

**Comment by knekkert** [comment] 2023-06-04 19:47
my perc h200 ontroller is not working on new loader

**Comment by AuxXxilium** [comment] 2023-06-04 19:53
you can add the module manual in loader.

**Comment by knekkert** [comment] 2023-06-04 19:55
it mode

**Comment by knekkert** [comment] 2023-06-04 20:01
can i select all modules?

**Comment by AuxXxilium** [comment] 2023-06-04 20:18
i don't think so. i need more time to find what is wrong.

but for now you can: deselect: scsi_transport_sas and scsi_transport_fc and try again.

**Comment by AuxXxilium** [comment] 2023-06-04 20:47
in about 15 minutes, do update modules (23.6.21e) and try again please. should fix your issue

**Comment by knekkert** [comment] 2023-06-04 21:15
23.6.21a
works! the lsi controller is detected!
thansk!!
good work

**Comment by AuxXxilium** [comment] 2023-06-04 21:29
thank you for report back, so now we have a stable tree

**Closed by AuxXxilium** 2023-06-04 21:29 UTC
Labels: bug, pending

**Comment by knekkert** [comment] 2023-06-04 22:02
Do you have a change log?

**Comment by AuxXxilium** [comment] 2023-06-04 22:14
look [Arc-Modules](https://github.com/AuxXxilium/arc-modules)

**Comment by knekkert** [comment] 2023-06-04 22:18
I tried te a release not e.

**Comment by AuxXxilium** [comment] 2023-06-05 04:46
what do you mean? there was never a te.

**Comment by serviceiotcc** [comment] 2023-06-05 12:45
I tried with the latest version of the bootloader (23.6.21e), the problem is fixed, thanks!
